#ifndef ERRLIST_H_
#define ERRLIST_H_

#define LEXEME_ERROR 'A'
#define SYNTAX_ERROR 'B'

enum Error {
    ILLEGAL_CHARSET = LEXEME_ERROR,
    ILLEGAL_HEX     = LEXEME_ERROR,
    ILLEGAL_CHAR    = LEXEME_ERROR,
    ILLEGAL_ID      = LEXEME_ERROR,
    ILLEGAL_OP      = LEXEME_ERROR,
    MISSING_SEMI    = SYNTAX_ERROR,
    MISSING_CLOSING = SYNTAX_ERROR,
    DEF_AFTER_STMT  = SYNTAX_ERROR,
};

#endif